version: "3"

services:
  app:
    build: .
    container_name: ifind_scripts_app
    environment:
      TORRC_PATH: /etc/tor/torrc
      MONGO_SERVER_URL: mongodb://ifind_scripts_db:27017/scripts_logs
    ports:
      - 3333:3333
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mongo
    container_name: ifind_scripts_db
    restart: always
    ports:
      - 27017:27017