version: "3"

services:
  app:
    build: .
    container_name: ifind_scripts_app
    environment:
      TORRC_PATH: /etc/tor/torrc
      MAIN_SERVER_URL: http://host.docker.internal:1337
      SHELL: /bin/bash # https://github.com/open-cli-tools/chokidar-cli/issues/62
      AIRTABLE_API_KEY: keyEA4usdufwK4na2 # Jayson's API_KEY
      AIRTABLE_BASE_SCHEDULED_TASKS: appNWlIhbI2h4pBGy # scheduled-tasks-dev base
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    # Required for WSL2 on Windows
    extra_hosts:
    - "host.docker.internal:host-gateway"
