version: "3"

services:
  app:
    build: .
    container_name: ifind_scripts_app
    environment:
      TORRC_PATH: /etc/tor/torrc
      MAIN_SERVER_URL: http://host.docker.internal:1337
      MONGO_SERVER_URL: mongodb://ifind_scripts_db:27017/scripts_server
      SHELL: /bin/bash # https://github.com/open-cli-tools/chokidar-cli/issues/62
    ports:
      - 3333:3333
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile:  DBDockerfile
    container_name: ifind_scripts_db
    restart: always
    ports:
      - 27017:27017